name: Validator

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      
permissions:
  checks: write
  contents: write
  packages: read
  
env:
  RUBY_VERSION: '3.2'

defaults:
  run:
    shell: bash

jobs:
  validator:
    name: Validator
    runs-on: ubuntu-latest
    steps:
      - name: Setup PSE
        uses: invisirisk/pse-action@latest
        with:
          api_url: "https://app.stage.invisirisk.com"
          app_token: ${{secrets.IR_API_KEY_VALIDATOR}}
      - id: checkout
        name: Checkout
        uses: actions/checkout@v4

      - id: setup-ruby
        name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true

      - id: install-gem
        name: Install gem
        run: |
          gem install awesome_bot --no-document

      - id: validate
        name: Validate
        continue-on-error: true
        run: |
          awesome_bot README.md --request-delay 0.5 --allow-timeout --allow-redirect
        
      - id: upload-artifact
        name: Upload artifact
        uses: actions/upload-artifact@v4
        if: ${{ failure() }}
        with:
          if-no-files-found: warn
          name: ab-results
          path: |
            ab-results-README.md.json
            ab-results-README.md-filtered.json
            ab-results-README.md-markdown-table.json
      - name: Cleanup PSE
        if: always()
        uses: invisirisk/pse-action@latest
        with:
          cleanup: "true"

  gather_status_validator:
    runs-on: ubuntu-latest
    name: Gather Status for validator
    needs: validator
    if: always()
    steps:
      - name: Gather Status
        uses: invisirisk/pse-action@latest
        with:
          api_url: "https://app.stage.invisirisk.com"
          app_token: ${{secrets.IR_API_KEY_VALIDATOR}}
          send_job_status: "true"
          debug: "true"
